name: flutter_clean_calendar
description: A new Flutter package project.
version: 0.1.2
author: "Carlos Peña <pmcarlosdev@gmail.com>"
homepage: "https://github.com/pmcarlos/flutter_clean_calendar"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_gesture_detector: ^0.1.0
  date_utils: ^0.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
